name: check-rs

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    paths: # Only run when changes are made to rust code or root Cargo
      - "crates/**"
      - "examples/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - "rustfmt.toml"
      - "clippy.toml"

# cancel previous job runs for the same workflow + pr
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-format-test:
    name: lint, format, spell check, test
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install toolchain
        run: rustup show

      - name: Pnpm Cache
        uses: ./.github/actions/pnpm-cache

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: check

      - name: Run test
        # We need to install sass first to enable sass-loader
        run: |
          node -e "console.log(process.arch)"
          cargo test --workspace  -- --nocapture --test-threads=1
